name: Release to Modrinth

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-daemon
      
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Find JAR file
      id: jar
      run: |
        JAR_FILE=$(find build/libs -name "*.jar" -not -name "*-sources.jar" -not -name "*-javadoc.jar" | head -1)
        echo "JAR_PATH=$JAR_FILE" >> $GITHUB_OUTPUT
        echo "JAR_NAME=$(basename $JAR_FILE)" >> $GITHUB_OUTPUT
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.jar.outputs.JAR_PATH }}
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload to Modrinth
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        modrinth-id: ${{ secrets.MODRINTH_PROJECT_ID }}
        modrinth-token: ${{ secrets.MODRINTH_PAT }}
        
        files: ${{ steps.jar.outputs.JAR_PATH }}
        name: "Candy Rush v${{ steps.version.outputs.VERSION }}"
        version: ${{ steps.version.outputs.VERSION }}
        version-type: release
        
        loaders: |
          spigot
          paper
          
        game-versions: |
          1.21.5
          
        dependencies: |
          spigot-api | suggests
          paper-api | suggests
          
        changelog-file: CHANGELOG.md
        
        retry-attempts: 2
        retry-delay: 10000